

main:
  - name: home
    url: /
    weight: 10
  - name: about
    url: /about/
    weight: 20

  - name: project
    url: /projects/
    weight: 30
    hasChildren: true
  - parent: project
    name: major
    url: /major/
    weight: 31
  - parent: project
    name: beside 
    url: /besides/
    weight: 33

  - name: experience
    url: /experiences/
    weight: 40
  - name: book
    url: /readings/
    weight: 50
  - name: contact
    url: /contacts/
    weight: 60