main:
  - name: 홈
    url: /
    weight: 10
  - name: 소개
    url: /about/
    weight: 20

  - name: 프로젝트
    url: /projects/
    weight: 30
    hasChildren: true
  - parent: 프로젝트
    name: 전공관련
    url: /major/
    weight: 31
  - parent: 프로젝트
    name: 그 외 
    url: /besides/
    weight: 33

  - name: 경험
    url: /experiences/
    weight: 40
  - name: 독서
    url: /readings/
    weight: 50
  - name: 연락
    url: /contacts/
    weight: 60
